name: build-image
on: 
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    validation:
        name: Valider les fichiers de config
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: s'assurer que packer est installe
              run: packer --version
            - name: s'assurer que ansible est installe
              run: ansible --version
            - name: s'assurer que openScap est installe
              run: oscap --version

            - name: installer ansible-lint
              run: python3 -m pip install --user ansible-lint

            - name: valider la format du packer
              working-directory: packer
              run: packer fmt -check .
            - name: valider la format d'ansible
              run: ansible-lint ansible/site.yml
            
    image-build:
        name: construction de l'image avec hardening
        runs-on: self-hosted
        needs: validation
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: installer les dependances ansible
              working-directory: ansible
              run: ansible-galaxy install -r requirements.yml

            - name: initialiser packer
              working-directory: packer
              run: packer init .

            - name: valider le packer
              working-directory: packer
              run: packer validate .
              
            - name: construire l'image
              working-directory: packer
              run: packer build -var-file=rocky.pkrvars.hcl .


    publication:
      name: publication d'image
      runs-on: self-hosted
      needs: image-build
      steps:
        - name: recuperer l'image construite
          uses: actions/download-artifact@v4
          with:
            name: rocky-image
        
        